<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>
      <UserSecretsId>e256631a-ab1e-4825-b97e-26978f4fb343</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentAssertions" Version="8.8.*" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="9.0.*" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.*" />
        <PackageReference Include="Moq" Version="4.20.*" />
        <PackageReference Include="NUnit" Version="4.4.*" />
        <PackageReference Include="NUnit3TestAdapter" Version="5.1.*">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="NUnit.Analyzers" Version="4.10.*">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="coverlet.collector" Version="6.0.*">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\ResourceProvisioner.API\ResourceProvisioner.API.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="appsettings.json">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <None Update="appsettings.Test.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>










