<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Azure.Core" Version="1.47.2.0" />
      <PackageReference Include="Azure.Identity" Version="1.14.*" />
      <PackageReference Include="Microsoft.Identity.Client" Version="4.74.*" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Datahub.Application\Datahub.Application.csproj" />
      <ProjectReference Include="..\Datahub.Core\Datahub.Core.csproj" />
    </ItemGroup>

</Project>


