# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/Datahub.Portal.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  
name: 2.0.$(date:yy)$(DayOfYear)$(rev:.r)  

steps:

- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: 5.0.x
    performMultiLevelLookup: true
    includePreviewVersions: true # Required for preview versions

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '$(solution)'
    arguments: '-r win-x64 --self-contained true'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'datahub-production-service-connection'
    appType: 'webApp'
    WebAppName: 'dh-portal-app-prd'
    packageForLinux: '$(System.DefaultWorkingDirectory)/WebPortal/**/*.zip'
    enableCustomDeployment: true
    DeploymentType: 'webDeploy'
