# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

variables:
  target_os: win-x64
  version.MajorMinor: 2.0
  version.Revision: $[counter(variables['version.MajorMinor'], 0)]
  system.debug: False

pool:
  vmImage: windows-latest

steps:
- script: echo FSDH - Building Desktop Uploader
  displayName: 'FSDH - Building Desktop Uploader'

- task: PowerShell@2
  displayName: 'dotnet publish Windows MSIX to $(Build.ArtifactStagingDirectory)'
  inputs:
    targetType: 'inline'
    script: |
      cd Desktop/Desktop.Uploader

      [IO.Directory]::SetCurrentDirectory((Convert-Path (Get-Location -PSProvider FileSystem)))
      $filetxt = [IO.File]::ReadAllText(".\Platforms\Windows\Package.appxmanifest") 
      $filetxt = $filetxt.replace("0.0.0.0","$(version.Revision)")
      $filetxt
      Set-Content -Path ".\Platforms\Windows\Package.appxmanifest" -Value $filetxt

- task: Bash@3
  displayName: Install .NET MAUI
  inputs:
    targetType: 'inline'
    script: |
        dotnet --version
        dotnet nuget locals all --clear
        dotnet workload install maui --source https://aka.ms/dotnet7/nuget/index.json --source https://api.nuget.org/v3/index.json
        dotnet workload install android ios maccatalyst tvos macos maui wasm-tools maui-maccatalyst --source https://aka.ms/dotnet7/nuget/index.json --source https://api.nuget.org/v3/index.json
        dotnet workload list

# https://docs.microsoft.com/en-us/dotnet/maui/windows/deployment/overview
- task: PowerShell@2
  displayName: 'dotnet publish Windows MSIX to $(Build.ArtifactStagingDirectory)'
  inputs:
    targetType: 'inline'
    script: |
      cd $(Build.SourcesDirectory)/Desktop/Desktop.Uploader
      dotnet publish -f net7.0-windows10.0.22621 -c Release -o $(Build.ArtifactStagingDirectory)

- task: PowerShell@2
  displayName: 'Locate and move MSIX'
  inputs:
    targetType: 'inline'
    script: |
      $msixPack = Get-ChildItem -Recurse -Include Desktop.Uploader*.msix -Path "$(Build.Repository.LocalPath)/*"
      Write-Host "Packaged MSIX File: $msixPack"
      Copy-Item $msixPack -Destination $(Build.ArtifactStagingDirectory)/
      $msixFinal= Get-ChildItem -Recurse -Include *.msix -Path "$(Build.ArtifactStagingDirectory)/*"
      Write-Host "##vso[task.setvariable variable=MSIX_FILE;]$msixFinal"

- task: DotNetCoreCLI@2
  displayName: 'Install Azure SignTool'
  inputs:
    command: custom
    custom: tool
    arguments: 'install --global AzureSignTool'

- task: AzureKeyVault@2
  displayName: "Get devops client ID and secret"
  inputs:
      azureSubscription: $(az_subscription)
      KeyVaultName: $(kv_name)
      SecretsFilter: 'devops-client-id, devops-client-secret'
      RunAsPreJob: True
- task: PowerShell@2
  displayName: 'Sign the package'
  inputs:
    targetType: 'inline'
    script: |
        & write-host "cid=$(devops-client-id), cst=$(devops-client-secret), file=$(MSIX_FILE)"
        & AzureSignTool sign -kvu ${env:cert_kv_url} -kvc ${env:cert_name} -kvi $(devops-client-id) -kvs "$(devops-client-secret)" -kvt ${env:cert_kv_tenant} -v "$(MSIX_FILE)"

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'fsdh-desktop-uploader'
