name: FSDH Integration Build

variables:
  target_os: linux-x64
  version.MajorMinor: 2.0
  version.Revision: $[counter(variables['version.MajorMinor'], 0)]
  
trigger:
  branches:
    include:
    - integration
  batch: True
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/integration
jobs:
- job: Job_1
  displayName: 'Agent job: prepare'
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
    clean: true
    lfs: true
    fetchTags: false
  - task: UseDotNet@2
    displayName: Use .NET Core sdk 8.0.x
    inputs:
      version: 8.0.x
      includePreviewVersions: true
      performMultiLevelLookup: true
  - task: NodeTool@0
    displayName: Use Node 15.11.0
    inputs:
      versionSpec: 15.11.0
  - task: PowerShell@2
    displayName: 'PowerShell Script: Set build number'
    inputs:
      targetType: inline
      script: |
        $dateCode = (Get-Date -Format 'yyyyMMdd')
        $buildName = "$(version.MajorMinor).$(version.Revision)_int_$dateCode"
        Write-Host "Setting the name of the build to '$buildName'."
        Write-Host "##vso[build.updatebuildnumber]$buildName"
        
- job: Job_2
  displayName: Agent job - build portal app
  dependsOn: Job_1
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
    clean: true
    lfs: true
    fetchTags: false
  - task: PowerShell@2
    displayName: PowerShell Script - copy appsettings
    inputs:
      targetType: inline
      script: |
        cd Portal/src
        $files=Get-Childitem -Path Datahub.Portal -Include appsettings*json-tmpl,launch*json-tmpl -File -Recurse -ErrorAction SilentlyContinue  | Where {$_.FullName -notlike "*\\Debug\\*"}
        foreach ($file in $files){
        $fileRendered=$file.FullName.trim("-tmpl")
        Write-Host "Processing file: ${file} > $fileRendered"
        Copy-Item $file.FullName -Force -Destination $fileRendered
        }
        cd Datahub.Portal; mv appsettings.Development.json appsettings.dev.json; Move-Item -Force appsettings.json-tmpl-spdatahub appsettings.json
  - task: DotNetCoreCLI@2
    displayName: dotnet restore
    inputs:
      command: restore
      projects: Portal/src/Datahub.Portal/*.csproj
  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      projects: Portal/src/Datahub.Portal/*.csproj
      arguments: --configuration $(BuildConfiguration)
  - task: DotNetCoreCLI@2
    displayName: dotnet publish
    inputs:
      projects: 'Portal/src/Datahub.Portal/*.csproj'
      command: publish
      arguments: -o $(Build.ArtifactStagingDirectory)/output/portal -r $(target_os) --self-contained true
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: datahub-portal-'
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)/output/portal
      ArtifactName: datahub-portal
      
- job: Job_3
  displayName: Agent job - build function app
  dependsOn: Job_1
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
    clean: true
    lfs: true
    fetchTags: false
  - task: DotNetCoreCLI@2
    displayName: dotnet restore
    inputs:
      command: restore
      projects: Portal/src/Datahub.Functions/*.csproj
  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      projects: Portal/src/Datahub.Functions/*.csproj
      arguments: --configuration $(BuildConfiguration)
  - task: DotNetCoreCLI@2
    displayName: dotnet publish
    inputs:
      command: publish
      publishWebProjects: false
      projects: Portal/src/Datahub.Functions/*.csproj
      arguments: -o $(Build.ArtifactStagingDirectory)/output/portal -r $(target_os) --self-contained true
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: datahub-function'
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)/output/portal
      ArtifactName: datahub-function
      
- job: Job_5
  displayName: Agent job - build resource provisioner function app
  dependsOn: Job_1
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
    clean: true
    lfs: true
    fetchTags: false
  - task: DotNetCoreCLI@2
    displayName: dotnet restore
    inputs:
      command: restore
      projects: ResourceProvisioner/src/ResourceProvisioner.Functions/*.csproj
  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      projects: ResourceProvisioner/src/ResourceProvisioner.Functions/*.csproj
      arguments: --configuration $(BuildConfiguration)
  - task: DotNetCoreCLI@2
    displayName: dotnet publish
    inputs:
      command: publish
      publishWebProjects: false
      projects: ResourceProvisioner/src/ResourceProvisioner.Functions/*.csproj
      arguments: -o $(Build.ArtifactStagingDirectory)/output/resourceprovisioner -r $(target_os) --self-contained true
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: resource-provisioner-function'
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)/output/resourceprovisioner
      ArtifactName: resource-provisioner-function
- job: Job_4
  displayName: Agent job - post-build
  dependsOn:
  - Job_1
  - Job_2
  - Job_3
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
    clean: true
    lfs: true
    fetchTags: false
    persistCredentials: True
  - task: PowerShell@2
    displayName: PowerShell Script
    env:
      MY_ACCESS_TOKEN: $(System.AccessToken)
    inputs:
      targetType: inline
      script: >-
        git config --global user.name "AzureDevOps Agent"

        $versionNumber="$(build.buildNumber)-int"


        git tag "$versionNumber" --force

        git push origin "$versionNumber" --force

        Write-Output "Tagging $(Build.Repository.Name) with $versionNumber-int"