# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

variables:
  target_os: win-x64
  version.MajorMinor: 2.0
  version.Revision: $[counter(variables['version.MajorMinor'], 0)]
  system.debug: true.

pool:
  vmImage: ubuntu-latest

steps:
- script: echo FSDH - Building Desktop Uploader
  displayName: 'FSDH - Building Desktop Uploader'

- task: DotNetCoreCLI@2
  displayName: dotnet restore
  inputs:
    command: restore
    projects: Desktop\Desktop.Uploader\*.csproj
    workingDirectory: $(Build.SourcesDirectory)

- task: DotNetCoreCLI@2
  displayName: dotnet build
  inputs:
    projects: Desktop\Desktop.Uploader\*.csproj
    arguments: --configuration $(BuildConfiguration)
    workingDirectory: $(Build.SourcesDirectory)

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: True
    projects: Desktop\Desktop.Uploader\Desktop.Uploader.csproj
    arguments: --output $(Build.ArtifactStagingDirectory) -r $(target_os) --self-contained true
    zipAfterPublish: True
    
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'fsdh-desktop-uploader'