# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

variables:
  target_os: win-x64
  version.MajorMinor: 2.0
  version.Revision: $[counter(variables['version.MajorMinor'], 0)]
  system.debug: True

pool:
  vmImage: windows-latest

steps:
- script: echo FSDH - Building Desktop Uploader
  displayName: 'FSDH - Building Desktop Uploader'

- task: UseDotNet@2
  inputs:
    version: 8.x
    packageType: 'sdk'
    includePreviewVersions: true

- task: Bash@3
  displayName: Install .NET MAUI
  inputs:
    targetType: 'inline'
    script: |
        dotnet --version
        dotnet nuget locals all --clear 
        dotnet workload install maui --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
        dotnet workload install android ios maccatalyst tvos macos maui wasm-tools --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
- task: DotNetCoreCLI@2
  displayName: dotnet restore
  inputs:
    command: restore
    projects: "**/Desktop.Uploader.csproj"
    workingDirectory: $(Build.SourcesDirectory)

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: True
    projects: Desktop\Desktop.Uploader\Desktop.Uploader.csproj
    arguments: -f net6.0-maccatalyst -c Release -p:BuildIpa=True -o $(Build.ArtifactStagingDirectory)
    zipAfterPublish: True
    
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'fsdh-desktop-uploader'