# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- script: echo FSDH - Building Desktop Uploader
  displayName: 'FSDH - Building Desktop Uploader'

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: True
    projects: Desktop\Desktop.Uploader\Desktop.Uploader.csproj
    arguments: '--output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True