<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>e256631a-ab1e-4825-b97e-26978f4fb343</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
                
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
        <PackageReference Include="Microsoft.Identity.Web" />
        <PackageReference Include="Microsoft.OpenApi" />
        <PackageReference Include="Swashbuckle.AspNetCore" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ResourceProvisioner.Application\ResourceProvisioner.Application.csproj" />
      <ProjectReference Include="..\ResourceProvisioner.Infrastructure\ResourceProvisioner.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="ResourceProvisioner.Application.IntegrationTests"></InternalsVisibleTo>
    </ItemGroup>

</Project>



