<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>
      <UserSecretsId>da17a412-9366-44ac-8f66-5506a1309391</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentAssertions" Version="8.8.*" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.*" />
        <PackageReference Include="NUnit" Version="4.4.*" />
        <PackageReference Include="NUnit3TestAdapter" Version="5.1.*" />
        <PackageReference Include="NUnit.Analyzers" Version="4.10.*">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="coverlet.collector" Version="6.0.*">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\ResourceProvisioner.Application\ResourceProvisioner.Application.csproj" />
    </ItemGroup>

</Project>









