name: Bug Report
description: File a bug report
labels: [triage]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report for [DataHub](https://github.com/ssc-sp/datahub-portal). Note that this template is only for bug reports. Please use [Github Dicussions](https://github.com/ssc-sp/datahub-portal/discussions) for any questions.
  - type: dropdown
    id: bug-type
    attributes:
      label: Bug type
      multiple: true
      options:
        - DataHub Portal
        - Databricks
        - Storage
        - Other
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please describe the issue briefly. You can use code-snippets, screenshots, gifs or videos to further explain your problem. Please post code-snippets surrounded in backticks and not as screenshots.
      placeholder: Describe your issue!
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Please provide a clear and concise description of what you expected to happen.
      placeholder: Describe the expected behavior!
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: Reproduction steps
      description: How do you trigger this bug? Please walk us through it step by step.
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      description: You don't have to test it on every browser.
      multiple: true
      options:
        - Firefox
        - Chrome
        - Microsoft Edge
        - Safari
        - Other
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: On what operating system are you experiencing the issue?
      description: You don't have to test it on every os.
      multiple: true
      options:
        - Windows
        - Mac OSX
        - Linux
        - Other
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree that none of the information provided is confidential.
      options:
        - label: I agree that none of the information provided is confidential. 
          required: true
