<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Reference Include="Microsoft.Extensions.Logging.Abstractions">
        <HintPath>..\WebPortal\bin\Debug\net6.0\Microsoft.Extensions.Logging.Abstractions.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MudBlazor" />
    	<PackageReference Include="Blazored.LocalStorage" />
		<PackageReference Include="Microsoft.AspNetCore.Components.Authorization" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
		<PackageReference Include="RulesEngine" />
	</ItemGroup>

    <ItemGroup>
      <Content Include="Achievements\**\*.achievement.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        <CopyToPublishDirectory>Always</CopyToPublishDirectory>
      </Content>
    </ItemGroup>

</Project>
