// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Datahub.Portal.Data.Finance;

namespace Datahub.Portal.Migrations.Forms.Finance
{
    [DbContext(typeof(FinanceDBContext))]
    partial class FinanceDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Datahub.Portal.Data.Finance.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("BranchNameEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchNameFr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SectorAndBranchForBranchId")
                        .HasColumnType("int");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.HasKey("BranchId");

                    b.HasIndex("SectorId");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            BranchId = 1,
                            BranchNameEn = "AUDIT & EVALUATION BRANCH",
                            BranchNameFr = "AUDIT & EVALUATION BRANCH",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 1
                        },
                        new
                        {
                            BranchId = 2,
                            BranchNameEn = "DEPUTY MINISTER'S OFFICES",
                            BranchNameFr = "DEPUTY MINISTER'S OFFICES",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 1
                        },
                        new
                        {
                            BranchId = 3,
                            BranchNameEn = "LEGAL SERVICES OFFICE",
                            BranchNameFr = "LEGAL SERVICES OFFICE",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 1
                        },
                        new
                        {
                            BranchId = 4,
                            BranchNameEn = "MINISTER'S OFFICE",
                            BranchNameFr = "MINISTER'S OFFICE",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 1
                        },
                        new
                        {
                            BranchId = 5,
                            BranchNameEn = "NRCAN CHARITABLE CAMPAIGN",
                            BranchNameFr = "NRCAN CHARITABLE CAMPAIGN",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 1
                        },
                        new
                        {
                            BranchId = 6,
                            BranchNameEn = "ADM'S OFFICE IAR SECTOR",
                            BranchNameFr = "ADM'S OFFICE IAR SECTOR",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 2
                        },
                        new
                        {
                            BranchId = 7,
                            BranchNameEn = "DGO",
                            BranchNameFr = "DGO",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 2
                        },
                        new
                        {
                            BranchId = 8,
                            BranchNameEn = "INDIGENOUS AFFAIRS AND RECON",
                            BranchNameFr = "INDIGENOUS AFFAIRS AND RECON",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 2
                        },
                        new
                        {
                            BranchId = 9,
                            BranchNameEn = "INDIGENOUS OUTREACH AND ENGAGEMENT",
                            BranchNameFr = "INDIGENOUS OUTREACH AND ENGAGEMENT",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 2
                        },
                        new
                        {
                            BranchId = 10,
                            BranchNameEn = "ADM’S OFFICE",
                            BranchNameFr = "ADM’S OFFICE",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 3
                        },
                        new
                        {
                            BranchId = 11,
                            BranchNameEn = "PUBLIC AFFAIRS BRANCH",
                            BranchNameFr = "PUBLIC AFFAIRS BRANCH",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 3
                        },
                        new
                        {
                            BranchId = 12,
                            BranchNameEn = "ENGAG DIGITAL COMMS",
                            BranchNameFr = "ENGAG DIGITAL COMMS",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 3
                        },
                        new
                        {
                            BranchId = 13,
                            BranchNameEn = "CPS CORP SERVICES",
                            BranchNameFr = "CPS CORP SERVICES",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 3
                        },
                        new
                        {
                            BranchId = 14,
                            BranchNameEn = "PORTFOLIO MGT & CORP SECRETARIAT BRANCH",
                            BranchNameFr = "PORTFOLIO MGT & CORP SECRETARIAT BRANCH",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 3
                        },
                        new
                        {
                            BranchId = 15,
                            BranchNameEn = "ADMO - SPPIO",
                            BranchNameFr = "ADMO - SPPIO",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 4
                        },
                        new
                        {
                            BranchId = 16,
                            BranchNameEn = "CANMET ENERGY - DEVON",
                            BranchNameFr = "CANMET ENERGY - DEVON",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 4
                        },
                        new
                        {
                            BranchId = 17,
                            BranchNameEn = "PETROLEUM RESOURCES BRANCH",
                            BranchNameFr = "PETROLEUM RESOURCES BRANCH",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 4
                        },
                        new
                        {
                            BranchId = 18,
                            BranchNameEn = "IND CONSULT FOR TMX",
                            BranchNameFr = "IND CONSULT FOR TMX",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 5
                        },
                        new
                        {
                            BranchId = 19,
                            BranchNameEn = "ATOMIC ENERGY",
                            BranchNameFr = "ATOMIC ENERGY",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 6
                        },
                        new
                        {
                            BranchId = 20,
                            BranchNameEn = "INDIGENOUS PARTNERSHIPS OFFICE - WEST",
                            BranchNameFr = "INDIGENOUS PARTNERSHIPS OFFICE - WEST",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 7
                        },
                        new
                        {
                            BranchId = 21,
                            BranchNameEn = "MAJOR PROJECT MANAGEMENT OFFICE",
                            BranchNameFr = "MAJOR PROJECT MANAGEMENT OFFICE",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 7
                        },
                        new
                        {
                            BranchId = 22,
                            BranchNameEn = "TMX ACCOMMODATION MEASURES",
                            BranchNameFr = "TMX ACCOMMODATION MEASURES",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 7
                        },
                        new
                        {
                            BranchId = 23,
                            BranchNameEn = "ASSISTANT DEPUTY MINISTER OFFICE",
                            BranchNameFr = "ASSISTANT DEPUTY MINISTER OFFICE",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 8
                        },
                        new
                        {
                            BranchId = 24,
                            BranchNameEn = "EXTERNAL POLICY & PARTNERSHIPS",
                            BranchNameFr = "EXTERNAL POLICY & PARTNERSHIPS",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 8
                        },
                        new
                        {
                            BranchId = 25,
                            BranchNameEn = "INNOVATION BRANCH",
                            BranchNameFr = "INNOVATION BRANCH",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 8
                        },
                        new
                        {
                            BranchId = 26,
                            BranchNameEn = "PARDP",
                            BranchNameFr = "PARDP",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 8
                        },
                        new
                        {
                            BranchId = 27,
                            BranchNameEn = "PLANNING, DELIVERY & RESULTS BRANCH",
                            BranchNameFr = "PLANNING, DELIVERY & RESULTS BRANCH",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 8
                        },
                        new
                        {
                            BranchId = 28,
                            BranchNameEn = "SECTOR FINANCIAL ADVISOR'S OFFICE SPRS",
                            BranchNameFr = "SECTOR FINANCIAL ADVISOR'S OFFICE SPRS",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 8
                        },
                        new
                        {
                            BranchId = 29,
                            BranchNameEn = "STRATEGIC POLICY BRANCH",
                            BranchNameFr = "STRATEGIC POLICY BRANCH",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 8
                        },
                        new
                        {
                            BranchId = 30,
                            BranchNameEn = "CANADA CENTRE FOR MAPPING AND EARTH OBS",
                            BranchNameFr = "CANADA CENTRE FOR MAPPING AND EARTH OBS",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 8
                        },
                        new
                        {
                            BranchId = 31,
                            BranchNameEn = "OCS - OPERATIONS",
                            BranchNameFr = "OCS - OPERATIONS",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 9
                        },
                        new
                        {
                            BranchId = 32,
                            BranchNameEn = "OFFICE OF THE CHIEF SCIENTIST",
                            BranchNameFr = "OFFICE OF THE CHIEF SCIENTIST",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 9
                        },
                        new
                        {
                            BranchId = 33,
                            BranchNameEn = "ADM’S OFFICE",
                            BranchNameFr = "ADM’S OFFICE",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 10
                        },
                        new
                        {
                            BranchId = 34,
                            BranchNameEn = "CLEAN FUELS BRANCH",
                            BranchNameFr = "CLEAN FUELS BRANCH",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 10
                        },
                        new
                        {
                            BranchId = 35,
                            BranchNameEn = "CORPORATE ACCOUNTS",
                            BranchNameFr = "CORPORATE ACCOUNTS",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 10
                        },
                        new
                        {
                            BranchId = 36,
                            BranchNameEn = "ELECTRICITY RESOURCES BRANCH",
                            BranchNameFr = "ELECTRICITY RESOURCES BRANCH",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 10
                        },
                        new
                        {
                            BranchId = 37,
                            BranchNameEn = "ENERGY POLICY BRANCH",
                            BranchNameFr = "ENERGY POLICY BRANCH",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 10
                        },
                        new
                        {
                            BranchId = 38,
                            BranchNameEn = "INTERNATIONAL ENERGY BRANCH",
                            BranchNameFr = "INTERNATIONAL ENERGY BRANCH",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 10
                        },
                        new
                        {
                            BranchId = 39,
                            BranchNameEn = "OFFICE OF ENERGY EFFICIENCY",
                            BranchNameFr = "OFFICE OF ENERGY EFFICIENCY",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 10
                        },
                        new
                        {
                            BranchId = 40,
                            BranchNameEn = "ADM'S OFFICE",
                            BranchNameFr = "ADM'S OFFICE",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 11
                        },
                        new
                        {
                            BranchId = 41,
                            BranchNameEn = "CHIEF INFORMATION AND SECURITY OFFICE",
                            BranchNameFr = "CHIEF INFORMATION AND SECURITY OFFICE",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 11
                        },
                        new
                        {
                            BranchId = 42,
                            BranchNameEn = "CMSS RESERVE",
                            BranchNameFr = "CMSS RESERVE",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 11
                        },
                        new
                        {
                            BranchId = 43,
                            BranchNameEn = "CORPORATE HR SERVICES & SYSTEMS",
                            BranchNameFr = "CORPORATE HR SERVICES & SYSTEMS",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 11
                        },
                        new
                        {
                            BranchId = 44,
                            BranchNameEn = "DEPARTMENTAL PROJECTS",
                            BranchNameFr = "DEPARTMENTAL PROJECTS",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 11
                        },
                        new
                        {
                            BranchId = 45,
                            BranchNameEn = "FACILITIES-REGIONS -EM-OHS",
                            BranchNameFr = "FACILITIES-REGIONS -EM-OHS",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 11
                        },
                        new
                        {
                            BranchId = 46,
                            BranchNameEn = "FINANCE AND PROCUREMENT BRANCH",
                            BranchNameFr = "FINANCE AND PROCUREMENT BRANCH",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 11
                        },
                        new
                        {
                            BranchId = 47,
                            BranchNameEn = "HUMAN RESOURCE /SECURITY MGMT BRANCH",
                            BranchNameFr = "HUMAN RESOURCE /SECURITY MGMT BRANCH",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 11
                        },
                        new
                        {
                            BranchId = 48,
                            BranchNameEn = "PLANNING AND OPERATION BRANCH",
                            BranchNameFr = "PLANNING AND OPERATION BRANCH",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 11
                        },
                        new
                        {
                            BranchId = 49,
                            BranchNameEn = "DEPARTMENTAL SERVICES - CIOSB",
                            BranchNameFr = "DEPARTMENTAL SERVICES - CIOSB",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 12
                        },
                        new
                        {
                            BranchId = 50,
                            BranchNameEn = "DEPARTMENTAL SERVICES - FPB",
                            BranchNameFr = "DEPARTMENTAL SERVICES - FPB",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 12
                        },
                        new
                        {
                            BranchId = 51,
                            BranchNameEn = "DEPARTMENTAL SERVICES - POB",
                            BranchNameFr = "DEPARTMENTAL SERVICES - POB",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 12
                        },
                        new
                        {
                            BranchId = 52,
                            BranchNameEn = "DEPARTMENTAL SERVICES - RP & FACILITIES",
                            BranchNameFr = "DEPARTMENTAL SERVICES - RP & FACILITIES",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 12
                        },
                        new
                        {
                            BranchId = 53,
                            BranchNameEn = "DEPARTMENTAL SERVICES - SUPPORT TO MINO",
                            BranchNameFr = "DEPARTMENTAL SERVICES - SUPPORT TO MINO",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 12
                        },
                        new
                        {
                            BranchId = 54,
                            BranchNameEn = "DEPTL SVCS - CORP HR SERVICES & SYSTEMS",
                            BranchNameFr = "DEPTL SVCS - CORP HR SERVICES & SYSTEMS",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 12
                        },
                        new
                        {
                            BranchId = 55,
                            BranchNameEn = "ADM’S OFFICE CFS",
                            BranchNameFr = "ADM’S OFFICE CFS",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 13
                        },
                        new
                        {
                            BranchId = 56,
                            BranchNameEn = "ATLANTIC FORESTRY CENTRE",
                            BranchNameFr = "ATLANTIC FORESTRY CENTRE",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 13
                        },
                        new
                        {
                            BranchId = 57,
                            BranchNameEn = "CANADIAN WOOD FIBRE CENTRE",
                            BranchNameFr = "CANADIAN WOOD FIBRE CENTRE",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 13
                        },
                        new
                        {
                            BranchId = 58,
                            BranchNameEn = "GREAT LAKES FORESTRY CENTER",
                            BranchNameFr = "GREAT LAKES FORESTRY CENTER",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 13
                        },
                        new
                        {
                            BranchId = 59,
                            BranchNameEn = "INTEGRATED SYSTEM APPLIED",
                            BranchNameFr = "INTEGRATED SYSTEM APPLIED",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 13
                        },
                        new
                        {
                            BranchId = 60,
                            BranchNameEn = "LAURENTIAN FOR CTR (INCL SUSPENSE ACCNT)",
                            BranchNameFr = "LAURENTIAN FOR CTR (INCL SUSPENSE ACCNT)",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 13
                        },
                        new
                        {
                            BranchId = 61,
                            BranchNameEn = "NORTHERN FORESTRY CENTRE",
                            BranchNameFr = "NORTHERN FORESTRY CENTRE",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 13
                        },
                        new
                        {
                            BranchId = 62,
                            BranchNameEn = "PACIFIC FORESTRY CENTRE",
                            BranchNameFr = "PACIFIC FORESTRY CENTRE",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 13
                        },
                        new
                        {
                            BranchId = 63,
                            BranchNameEn = "PLANNING OPERATIONS AND INFORMATION",
                            BranchNameFr = "PLANNING OPERATIONS AND INFORMATION",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 13
                        },
                        new
                        {
                            BranchId = 64,
                            BranchNameEn = "POLICY ECONOMICS INTERNATIONAL &INDUSTRY",
                            BranchNameFr = "POLICY ECONOMICS INTERNATIONAL &INDUSTRY",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 13
                        },
                        new
                        {
                            BranchId = 65,
                            BranchNameEn = "SCIENCE POLICY INTEGRATION",
                            BranchNameFr = "SCIENCE POLICY INTEGRATION",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 13
                        },
                        new
                        {
                            BranchId = 66,
                            BranchNameEn = "ADM’S RESERVE",
                            BranchNameFr = "ADM’S RESERVE",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 14
                        },
                        new
                        {
                            BranchId = 67,
                            BranchNameEn = "CANMET ENERGY – OTTAWA",
                            BranchNameFr = "CANMET ENERGY – OTTAWA",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 14
                        },
                        new
                        {
                            BranchId = 68,
                            BranchNameEn = "CANMET ENERGY – VARENNES",
                            BranchNameFr = "CANMET ENERGY – VARENNES",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 14
                        },
                        new
                        {
                            BranchId = 69,
                            BranchNameEn = "CANMET MATERIALS",
                            BranchNameFr = "CANMET MATERIALS",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 14
                        },
                        new
                        {
                            BranchId = 70,
                            BranchNameEn = "ETS ADM'S OFFICE",
                            BranchNameFr = "ETS ADM'S OFFICE",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 14
                        },
                        new
                        {
                            BranchId = 71,
                            BranchNameEn = "FINANCE MANAGEMENT",
                            BranchNameFr = "FINANCE MANAGEMENT",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 14
                        },
                        new
                        {
                            BranchId = 72,
                            BranchNameEn = "OFFICE OF ENERGY RESEARCH AND DEV",
                            BranchNameFr = "OFFICE OF ENERGY RESEARCH AND DEV",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 14
                        },
                        new
                        {
                            BranchId = 73,
                            BranchNameEn = "PLANNING & OPERATIONS",
                            BranchNameFr = "PLANNING & OPERATIONS",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 14
                        },
                        new
                        {
                            BranchId = 74,
                            BranchNameEn = "SECTOR MANAGEMENT ACCOUNT",
                            BranchNameFr = "SECTOR MANAGEMENT ACCOUNT",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 14
                        },
                        new
                        {
                            BranchId = 75,
                            BranchNameEn = "ADM’S OFFICE",
                            BranchNameFr = "ADM’S OFFICE",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 15
                        },
                        new
                        {
                            BranchId = 76,
                            BranchNameEn = "BUSINESS MANAGEMENT SERVICES AND DATA",
                            BranchNameFr = "BUSINESS MANAGEMENT SERVICES AND DATA",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 15
                        },
                        new
                        {
                            BranchId = 77,
                            BranchNameEn = "CANMET MINES",
                            BranchNameFr = "CANMET MINES",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 15
                        },
                        new
                        {
                            BranchId = 78,
                            BranchNameEn = "EXPLOSIVE SAFETY & SECURITY BRANCH",
                            BranchNameFr = "EXPLOSIVE SAFETY & SECURITY BRANCH",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 15
                        },
                        new
                        {
                            BranchId = 79,
                            BranchNameEn = "GEOLOGICAL SURVEY OF CANADA",
                            BranchNameFr = "GEOLOGICAL SURVEY OF CANADA",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 15
                        },
                        new
                        {
                            BranchId = 80,
                            BranchNameEn = "HAZ ADAP & OPS BR",
                            BranchNameFr = "HAZ ADAP & OPS BR",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 15
                        },
                        new
                        {
                            BranchId = 81,
                            BranchNameEn = "LANDS & MINERALS SECTOR RESERVE",
                            BranchNameFr = "LANDS & MINERALS SECTOR RESERVE",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 15
                        },
                        new
                        {
                            BranchId = 82,
                            BranchNameEn = "POLICY AND ECONOMICS BRANCH",
                            BranchNameFr = "POLICY AND ECONOMICS BRANCH",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 15
                        },
                        new
                        {
                            BranchId = 83,
                            BranchNameEn = "SURVEYOR GENERAL BRANCH",
                            BranchNameFr = "SURVEYOR GENERAL BRANCH",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 15
                        },
                        new
                        {
                            BranchId = 84,
                            BranchNameEn = "CASH IN HANDS & IN TRANSIT",
                            BranchNameFr = "CASH IN HANDS & IN TRANSIT",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 16
                        },
                        new
                        {
                            BranchId = 85,
                            BranchNameEn = "CASH RECEIPTS SUSPENSE",
                            BranchNameFr = "CASH RECEIPTS SUSPENSE",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 16
                        },
                        new
                        {
                            BranchId = 86,
                            BranchNameEn = "CORPORATE ACCOUNTING - ACCRUALS",
                            BranchNameFr = "CORPORATE ACCOUNTING - ACCRUALS",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 16
                        },
                        new
                        {
                            BranchId = 87,
                            BranchNameEn = "EMPLOYEE BENEFIT PLAN",
                            BranchNameFr = "EMPLOYEE BENEFIT PLAN",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 16
                        },
                        new
                        {
                            BranchId = 88,
                            BranchNameEn = "GARNISHEED SALARIES",
                            BranchNameFr = "GARNISHEED SALARIES",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 16
                        },
                        new
                        {
                            BranchId = 89,
                            BranchNameEn = "GST COLLECTED",
                            BranchNameFr = "GST COLLECTED",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 16
                        },
                        new
                        {
                            BranchId = 90,
                            BranchNameEn = "GST PAID - PURCHASES",
                            BranchNameFr = "GST PAID - PURCHASES",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 16
                        },
                        new
                        {
                            BranchId = 91,
                            BranchNameEn = "INTEREST EARNED",
                            BranchNameFr = "INTEREST EARNED",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 16
                        },
                        new
                        {
                            BranchId = 92,
                            BranchNameEn = "IS SUSPEND-EXPENDITURES",
                            BranchNameFr = "IS SUSPEND-EXPENDITURES",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 16
                        },
                        new
                        {
                            BranchId = 93,
                            BranchNameEn = "MONIES REC'D AFTER MARCH 31 - OLD YEAR",
                            BranchNameFr = "MONIES REC'D AFTER MARCH 31 - OLD YEAR",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 16
                        },
                        new
                        {
                            BranchId = 94,
                            BranchNameEn = "PAYROLL DEDUCTIONS - PHOENIX DAMAGES",
                            BranchNameFr = "PAYROLL DEDUCTIONS - PHOENIX DAMAGES",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 16
                        },
                        new
                        {
                            BranchId = 95,
                            BranchNameEn = "PROCEEDS CROWN ASSET DISPOSAL",
                            BranchNameFr = "PROCEEDS CROWN ASSET DISPOSAL",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 16
                        },
                        new
                        {
                            BranchId = 96,
                            BranchNameEn = "PST COLLECTED",
                            BranchNameFr = "PST COLLECTED",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 16
                        },
                        new
                        {
                            BranchId = 97,
                            BranchNameEn = "QST PAID ON PURCHASE (8530)",
                            BranchNameFr = "QST PAID ON PURCHASE (8530)",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 16
                        },
                        new
                        {
                            BranchId = 98,
                            BranchNameEn = "RF CORPORATE ACCOUNTING - ACCRUALS",
                            BranchNameFr = "RF CORPORATE ACCOUNTING - ACCRUALS",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 16
                        },
                        new
                        {
                            BranchId = 99,
                            BranchNameEn = "RF EMPLOYEE BENEFIT PLAN",
                            BranchNameFr = "RF EMPLOYEE BENEFIT PLAN",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 16
                        },
                        new
                        {
                            BranchId = 100,
                            BranchNameEn = "RF INTEREST EARNED",
                            BranchNameFr = "RF INTEREST EARNED",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 16
                        },
                        new
                        {
                            BranchId = 101,
                            BranchNameEn = "SFT DEFAULT",
                            BranchNameFr = "SFT DEFAULT",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 16
                        },
                        new
                        {
                            BranchId = 102,
                            BranchNameEn = "SSO AMEX/MASTERCARD DEFAULT",
                            BranchNameFr = "SSO AMEX/MASTERCARD DEFAULT",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 16
                        },
                        new
                        {
                            BranchId = 103,
                            BranchNameEn = "TRAVELLERS CHEQUES - CLEARING ACCOUNT",
                            BranchNameFr = "TRAVELLERS CHEQUES - CLEARING ACCOUNT",
                            SectorAndBranchForBranchId = 0,
                            SectorId = 16
                        });
                });

            modelBuilder.Entity("Datahub.Portal.Data.Finance.Budget", b =>
                {
                    b.Property<int>("Budget_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double?>("Adjustments_To_Forecast_NUM")
                        .HasColumnType("float");

                    b.Property<double?>("Allocation_Percentage_NUM")
                        .HasColumnType("float");

                    b.Property<double?>("Anticipated_Transfers_NUM")
                        .HasColumnType("float");

                    b.Property<double?>("Budget_NUM")
                        .HasColumnType("float");

                    b.Property<string>("Comments_Notes_For_Financial_Information_TXT")
                        .HasMaxLength(7500)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comments_Notes_For_NonFinancial_Information_TXT")
                        .HasMaxLength(7500)
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Contributions_NUM")
                        .HasColumnType("float");

                    b.Property<string>("Departmental_Priorities_TXT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Determinate_Fte_NUM")
                        .HasColumnType("float");

                    b.Property<double?>("Determinate__Amount_NUM")
                        .HasColumnType("float");

                    b.Property<double>("Division_NUM")
                        .HasColumnType("float");

                    b.Property<double?>("Forecast_Adjustment_For_Risk_Management_NUM")
                        .HasColumnType("float");

                    b.Property<double?>("Forecast_Adjustment_For_Salary_Attrition_NUM")
                        .HasColumnType("float");

                    b.Property<int?>("Fund_NUM")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Funding_Type_TXT")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double?>("Grants_NUM")
                        .HasColumnType("float");

                    b.Property<double?>("Indeterminate_Fte_NUM")
                        .HasColumnType("float");

                    b.Property<double?>("Indeterminate__Amount_NUM")
                        .HasColumnType("float");

                    b.Property<double?>("Information_NUM")
                        .HasColumnType("float");

                    b.Property<double?>("Information_Three_Year_Average_NUM")
                        .HasColumnType("float");

                    b.Property<string>("Involves_An_It_Or_Real_Property_Component_TXT")
                        .HasMaxLength(7500)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key_Activity_TXT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Last_Updated_DT")
                        .HasColumnType("datetime2");

                    b.Property<string>("Last_Updated_UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Machine_and_Equipment_NUM")
                        .HasColumnType("float");

                    b.Property<double?>("Machine_and_Equipment_Three_Year_Average_NUM")
                        .HasColumnType("float");

                    b.Property<double?>("NonPersonnel_NUM")
                        .HasColumnType("float");

                    b.Property<double?>("Other_Payments_and_Ogd_Recoveries_NUM")
                        .HasColumnType("float");

                    b.Property<double?>("Other_Payments_and_Ogd_Recoveries_Three_Year_Average_NUM")
                        .HasColumnType("float");

                    b.Property<double?>("Percent_Of_Forecast_To_Budget_NUM")
                        .HasColumnType("float");

                    b.Property<double?>("Personnel_NUM")
                        .HasColumnType("float");

                    b.Property<double?>("Planned_Staffing_Fte_NUM")
                        .HasColumnType("float");

                    b.Property<double?>("Planned_Staffing__Amount_NUM")
                        .HasColumnType("float");

                    b.Property<double?>("Professional_SeervicesThree_Year_Average_NUM")
                        .HasColumnType("float");

                    b.Property<double?>("Professional_Seervices_NUM")
                        .HasColumnType("float");

                    b.Property<string>("Program_Activity_TXT")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double?>("Rentals_NUM")
                        .HasColumnType("float");

                    b.Property<double?>("Rentals_Three_Year_Average_NUM")
                        .HasColumnType("float");

                    b.Property<double?>("Repairs_and_MaintenanceThree_Year_Average_NUM")
                        .HasColumnType("float");

                    b.Property<double?>("Repairs_and_Maintenance_NUM")
                        .HasColumnType("float");

                    b.Property<int?>("SectorAndBranchSectorBranch_ID")
                        .HasColumnType("int");

                    b.Property<string>("Sector_Priorities_TXT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubLevel_TXT")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<double?>("Transportation_and_Communication_NUM")
                        .HasColumnType("float");

                    b.Property<double?>("Transportation_and_Communication_Three_Year_Average_NUM")
                        .HasColumnType("float");

                    b.Property<double?>("Utilities_Materials_and_Supplies_NUM")
                        .HasColumnType("float");

                    b.Property<double?>("Utilities_Materials_and_Supplies_Three_Year_Average_NUM")
                        .HasColumnType("float");

                    b.HasKey("Budget_ID");

                    b.HasIndex("SectorAndBranchSectorBranch_ID");

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("Datahub.Portal.Data.Finance.Sector", b =>
                {
                    b.Property<int>("SectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("SectorAndBranchForSectorId")
                        .HasColumnType("int");

                    b.Property<string>("SectorNameEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectorNameFr")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SectorId");

                    b.ToTable("Sectors");

                    b.HasData(
                        new
                        {
                            SectorId = 1,
                            SectorAndBranchForSectorId = 0,
                            SectorNameEn = "DIRECTION AND COORDINATION",
                            SectorNameFr = "DIRECTION AND COORDINATION"
                        },
                        new
                        {
                            SectorId = 2,
                            SectorAndBranchForSectorId = 0,
                            SectorNameEn = "INDIGENOUS AFFAIRS AND RECON SECTOR",
                            SectorNameFr = "INDIGENOUS AFFAIRS AND RECON SECTOR"
                        },
                        new
                        {
                            SectorId = 3,
                            SectorAndBranchForSectorId = 0,
                            SectorNameEn = "COMMS PORTFOLIO SEC",
                            SectorNameFr = "COMMS PORTFOLIO SEC"
                        },
                        new
                        {
                            SectorId = 4,
                            SectorAndBranchForSectorId = 0,
                            SectorNameEn = "STRATEGIC PETROLEUM POL & INV OFFICE",
                            SectorNameFr = "STRATEGIC PETROLEUM POL & INV OFFICE"
                        },
                        new
                        {
                            SectorId = 5,
                            SectorAndBranchForSectorId = 0,
                            SectorNameEn = "IND CONSULT FOR TMX",
                            SectorNameFr = "IND CONSULT FOR TMX"
                        },
                        new
                        {
                            SectorId = 6,
                            SectorAndBranchForSectorId = 0,
                            SectorNameEn = "ATOMIC ENERGY SECTOR",
                            SectorNameFr = "ATOMIC ENERGY SECTOR"
                        },
                        new
                        {
                            SectorId = 7,
                            SectorAndBranchForSectorId = 0,
                            SectorNameEn = "MAJOR PROJECT MANAGEMENT OFFICE SECTOR",
                            SectorNameFr = "MAJOR PROJECT MANAGEMENT OFFICE SECTOR"
                        },
                        new
                        {
                            SectorId = 8,
                            SectorAndBranchForSectorId = 0,
                            SectorNameEn = "STRATEGIC POLICY AND INNOVATION",
                            SectorNameFr = "STRATEGIC POLICY AND INNOVATION"
                        },
                        new
                        {
                            SectorId = 9,
                            SectorAndBranchForSectorId = 0,
                            SectorNameEn = "OFFICE OF THE CHIEF SCIENTIST",
                            SectorNameFr = "OFFICE OF THE CHIEF SCIENTIST"
                        },
                        new
                        {
                            SectorId = 10,
                            SectorAndBranchForSectorId = 0,
                            SectorNameEn = "LOW CARBON ENERGY SECTOR",
                            SectorNameFr = "LOW CARBON ENERGY SECTOR"
                        },
                        new
                        {
                            SectorId = 11,
                            SectorAndBranchForSectorId = 0,
                            SectorNameEn = "CORPORATE MANAGEMENT AND SERVICES SECTOR",
                            SectorNameFr = "CORPORATE MANAGEMENT AND SERVICES SECTOR"
                        },
                        new
                        {
                            SectorId = 12,
                            SectorAndBranchForSectorId = 0,
                            SectorNameEn = "DEPARTMENTAL SERVICES",
                            SectorNameFr = "DEPARTMENTAL SERVICES"
                        },
                        new
                        {
                            SectorId = 13,
                            SectorAndBranchForSectorId = 0,
                            SectorNameEn = "CANADIAN FOREST SERVICE",
                            SectorNameFr = "CANADIAN FOREST SERVICE"
                        },
                        new
                        {
                            SectorId = 14,
                            SectorAndBranchForSectorId = 0,
                            SectorNameEn = "ENERGY TECHNOLOGY SECTOR",
                            SectorNameFr = "ENERGY TECHNOLOGY SECTOR"
                        },
                        new
                        {
                            SectorId = 15,
                            SectorAndBranchForSectorId = 0,
                            SectorNameEn = "LANDS AND MINERALS SECTOR",
                            SectorNameFr = "LANDS AND MINERALS SECTOR"
                        },
                        new
                        {
                            SectorId = 16,
                            SectorAndBranchForSectorId = 0,
                            SectorNameEn = "CORPORATE ACCOUNTING",
                            SectorNameFr = "CORPORATE ACCOUNTING"
                        });
                });

            modelBuilder.Entity("Datahub.Portal.Data.Finance.SectorAndBranch", b =>
                {
                    b.Property<int>("SectorBranch_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal?>("Allocated_Budget_NUM")
                        .HasColumnType("Money");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Branch_Budget_NUM")
                        .HasColumnType("Money");

                    b.Property<string>("Branch_TXT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Last_Updated_DT")
                        .HasColumnType("datetime2");

                    b.Property<string>("Last_Updated_UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SectorId")
                        .HasColumnType("int");

                    b.Property<string>("Sector_TXT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal?>("Unallocated_Budget_NUM")
                        .HasColumnType("Money");

                    b.HasKey("SectorBranch_ID");

                    b.HasIndex("BranchId");

                    b.HasIndex("SectorId");

                    b.ToTable("SectorAndBranches");
                });

            modelBuilder.Entity("Datahub.Portal.Data.Finance.Branch", b =>
                {
                    b.HasOne("Datahub.Portal.Data.Finance.Sector", "Sector")
                        .WithMany("Branches")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("Datahub.Portal.Data.Finance.Budget", b =>
                {
                    b.HasOne("Datahub.Portal.Data.Finance.SectorAndBranch", "SectorAndBranch")
                        .WithMany()
                        .HasForeignKey("SectorAndBranchSectorBranch_ID");

                    b.Navigation("SectorAndBranch");
                });

            modelBuilder.Entity("Datahub.Portal.Data.Finance.SectorAndBranch", b =>
                {
                    b.HasOne("Datahub.Portal.Data.Finance.Branch", "Branch")
                        .WithMany("SectorAndBranch")
                        .HasForeignKey("BranchId");

                    b.HasOne("Datahub.Portal.Data.Finance.Sector", "Sector")
                        .WithMany("SectorAndBranch")
                        .HasForeignKey("SectorId");

                    b.Navigation("Branch");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("Datahub.Portal.Data.Finance.Branch", b =>
                {
                    b.Navigation("SectorAndBranch");
                });

            modelBuilder.Entity("Datahub.Portal.Data.Finance.Sector", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("SectorAndBranch");
                });
#pragma warning restore 612, 618
        }
    }
}
