<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Datahub.SpecflowTests</RootNamespace>
		<IsTestProject>true</IsTestProject>
      <UserSecretsId>0e5da883-04b1-4ef6-87a0-33f222cc5391</UserSecretsId>
      <!-- Workaround for Reqnroll with .NET 9 SDK -->
      <ReqnrollGeneratorRuntime>NetCore</ReqnrollGeneratorRuntime>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.20.*" />
        <PackageReference Include="Azure.ResourceManager.Billing" Version="1.2.*" />
        <PackageReference Include="Azure.ResourceManager.Consumption" Version="1.0.*" />
        <PackageReference Include="Azure.ResourceManager.Resources" Version="1.11.*" />
        <PackageReference Include="bunit" Version="2.1.*" />
		<PackageReference Include="bunit.generators" Version="2.1.*" />
        <PackageReference Include="Deque.AxeCore.Commons" Version="4.10.*" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.*" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.*" />
        <PackageReference Include="NSubstitute" Version="5.3.*" />
        <PackageReference Include="NSubstitute.Analyzers.CSharp" Version="1.0.*">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="NUnit.ConsoleRunner" Version="3.20.*" />
        <PackageReference Include="FluentAssertions" Version="8.8.0" />
        <PackageReference Include="Reqnroll" Version="3.2.1" />
        <PackageReference Include="Reqnroll.xUnit.v3" Version="3.2.1" />
		<PackageReference Include="coverlet.collector" Version="6.0.*">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
		<PackageReference Include="xunit.v3" Version="3.2.0" />
		<PackageReference Include="xunit.runner.visualstudio" Version="3.1.*">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\ServerlessOperations\src\Datahub.Functions\Datahub.Functions.csproj" />
      <ProjectReference Include="..\..\src\Datahub.Infrastructure.Offline\Datahub.Infrastructure.Offline.csproj" />
      <ProjectReference Include="..\..\src\Datahub.Portal\Datahub.Portal.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="Features\**\*.feature" />
    </ItemGroup>

</Project>













