<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Datahub.SpecflowTests</RootNamespace>
		<IsTestProject>true</IsTestProject>
      <UserSecretsId>0e5da883-04b1-4ef6-87a0-33f222cc5391</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.20.*" />
        <PackageReference Include="Azure.ResourceManager.Billing" Version="1.2.*" />
        <PackageReference Include="Azure.ResourceManager.Consumption" Version="1.0.*" />
        <PackageReference Include="Azure.ResourceManager.Resources" Version="1.11.*" />
        <PackageReference Include="bunit" Version="1.40.*" />
        <PackageReference Include="Deque.AxeCore.Commons" Version="4.10.*" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.*" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.*" />
        <PackageReference Include="NSubstitute" Version="5.3.*" />
        <PackageReference Include="NSubstitute.Analyzers.CSharp" Version="1.0.*">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="NUnit.ConsoleRunner" Version="3.20.*" />
        <PackageReference Include="FluentAssertions" Version="8.5.*" />
        <PackageReference Include="Reqnroll" Version="2.4.*" />
        <PackageReference Include="Reqnroll.xUnit" Version="2.4.*" />
        <PackageReference Include="xunit" Version="2.9.*" />
		<PackageReference Include="xunit.runner.visualstudio" Version="3.1.*">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="coverlet.collector" Version="6.0.*">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\ServerlessOperations\src\Datahub.Functions\Datahub.Functions.csproj" />
      <ProjectReference Include="..\..\src\Datahub.Infrastructure.Offline\Datahub.Infrastructure.Offline.csproj" />
      <ProjectReference Include="..\..\src\Datahub.Portal\Datahub.Portal.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="Features\**\*.feature" />
    </ItemGroup>

</Project>













