<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Datahub.Core\Datahub.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Azure.Core" Version="1.52.*" />
		<PackageReference Include="Azure.Identity" Version="1.20.*" />
		<PackageReference Include="Azure.ResourceManager" Version="1.13.*" />
		<PackageReference Include="Microsoft.Identity.Client" Version="4.83.*" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.*" />
		<PackageReference Include="Yarp.ReverseProxy" Version="2.3.*" />
	</ItemGroup>

</Project>







