---
name: 1. Create Release

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: release-manager-create-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release-please:
    environment: datahub-portal-releases
    runs-on: ubuntu-latest
    steps:
      - name: Convert App token
        id: create_token
        uses: getsentry/action-github-app-token@5c1e90706fe007857338ac1bfbd7a4177db2f789 # v4.0.0
        with:
          app_id: ${{ vars.DH_RELEASE_MANAGER_ID }}
          private_key: ${{ secrets.DH_RELEASE_MANAGER_KEY }}

      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5
        with:
          target-branch: develop
          release-type: simple
          config-file: .release-please-config.json
          token: ${{ steps.create_token.outputs.token }}
