name: Integration CI/CD

on:
  schedule:
  - cron: "0 6 * * 1"
  
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge development -> integration
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: development
          target_branch: integration
          github_token: ${{ secrets.GITHUB_TOKEN }}
