---
name: Secret scanning

on:
  pull_request:
    branches:
      - develop

permissions: read-all

jobs:
  pr-secret-scan:
    name: Secret scan PR changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR source
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          persist-credentials: false

      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@37b77001d0174ebec2fcca2bd83ff83a6d45a3ab # v3.95.3
        with:
          path: ./
          base: ${{ github.event.pull_request.base.sha }}
          head: ${{ github.event.pull_request.head.sha }}
          extra_args: --results=verified,unknown
