---
name: 2. Release to Proof-of-concept branch

on:
  release:
    types: [released]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Convert App token
        id: create_token 
        uses: actions/create-github-app-token@7e473efe3cb98aa54f8d4bac15400b15fad77d94 # v2
        with:
          app-id:: ${{ vars.DH_RELEASE_MANAGER_ID }}
          private-key: ${{ secrets.DH_RELEASE_MANAGER_KEY }}

      - name: Checkout proof-of-concept branch
        uses: actions/checkout@v4
        with:
          ref: proof-of-concept
          token: ${{ steps.create_token.outputs.token }}
          fetch-depth: 1

      - name: Ensure Release is from Develop
        run: |
          TARGET="${{ github.event.release.target_commitish }}"
          echo "Release target: $TARGET"
          
          if [ "$TARGET" != "develop" ]; then
            echo "Skipping: Release was targeted at '$TARGET', not 'develop'."
            exit 0 
          fi

      - name: Fetch the Release Tag
        run: git fetch origin ${{ github.ref }} --depth=1

      - name: Output Release Info
        run: |
          echo "Deploying Release Version: ${{ github.event.release.tag_name }}"
          echo "Commit SHA: ${{ github.sha }}"

      - name: Hard-reset proof-of-concept to Release
        run: |
          git reset --hard ${{ github.sha }}
          git push origin proof-of-concept --force-with-lease
        env:
          GITHUB_TOKEN: ${{ steps.create_token.outputs.token }}