---
name: 2. Release to Proof-of-concept branch

on:
  release:
    types: [released]

permissions: read-all

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Convert App token
        id: create_token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        with:
          app-id:: ${{ vars.DH_RELEASE_MANAGER_ID }}
          private-key: ${{ secrets.DH_RELEASE_MANAGER_KEY }}

      - name: Checkout proof-of-concept branch
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1
        with:
          ref: proof-of-concept
          fetch-depth: 1
          persist-credentials: false
        env:
          GITHUB_TOKEN: ${{ steps.create_token.outputs.token }}

      - name: Ensure Release is from Develop
        run: |
          TARGET="${GITHUB_EVENT_RELEASE_TARGET_COMMITISH}"
          echo "Release target: $TARGET"

          if [ "$TARGET" != "develop" ]; then
            echo "Skipping: Release was targeted at '$TARGET', not 'develop'."
            exit 0
          fi
        env:
          GITHUB_EVENT_RELEASE_TARGET_COMMITISH: ${{ github.event.release.target_commitish }}

      - name: Fetch the Release Tag
        run: git fetch origin "${GITHUB_REF}" --depth=1

      - name: Output Release Info
        run: |
          echo "Deploying Release Version: ${GITHUB_EVENT_RELEASE_TAG_NAME}"
          echo "Commit SHA: ${{ github.sha }}"
        env:
          GITHUB_EVENT_RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}

      - name: Hard-reset proof-of-concept to Release
        run: |
          git reset --hard ${{ github.sha }}
          git push origin proof-of-concept --force-with-lease
        env:
          GITHUB_TOKEN: ${{ steps.create_token.outputs.token }}
