---
name: Pull request update

on:
  push:
    branches:
      - develop
      - auto-update-v2
    workflow_dispatch: {}

jobs:
  refresh_stale_prs:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Update ALL THE PRS! 🎉
        uses: DiegoRamil/actions-pr-auto-update@v1.0.4
        with:
           defaults to github.token
          token: ${{ secrets.GITHUB_TOKEN }}
          # Optional: include a limit to the number of PRs to update (default is 100)
          limit: 20
          # Optional: set this to true if you want to include draft PRs in those to be updated
          include_drafts: true
          # Optional: include a list of labels which, if present, will prevent the PR from being updated; these are comma-separated.
          exclude_labels: "do not update,skip update"
          # Optional: include a list of labels, at least one of which are required to be present for the PR to be updated; these are comma-separated.
          #include_labels: 'update,update me'
