on:
  push:
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write

name: Release-Manager

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          target-branch: release
          release-type: simple
          config-file: .release-please-config.json