<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="LibGit2SharpFork" />
      <PackageReference Include="Microsoft.AspNetCore.Http" />
      <PackageReference Include="Microsoft.Extensions.Http" />
      <PackageReference Include="Microsoft.FeatureManagement" />
      <PackageReference Include="Polly" />
      
    </ItemGroup>


    <ItemGroup>
        <InternalsVisibleTo Include="ResourceProvisioner.Infrastructure.UnitTests"></InternalsVisibleTo>
        <InternalsVisibleTo Include="ResourceProvisioner.SpecflowTests"></InternalsVisibleTo>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ResourceProvisioner.Application\ResourceProvisioner.Application.csproj" />
    </ItemGroup>
</Project>






